### PR TITLE
zig 15.1

### LINKED ISSUE #5: Can't build with zig 15.1
```
zig build-exe src/zwmcmd.zig -lc -lX11 -lXft -I/usr/include/freetype2
src/zwmcmd.zig:11:9: error: local variable is never mutated
    var arg_one = args.next() orelse return usage();
        ^~~~~~~
src/zwmcmd.zig:11:9: note: consider using 'const'
src/zwmcmd.zig:30:9: error: local variable is never mutated
    var root = c.XDefaultRootWindow(display);
        ^~~~
src/zwmcmd.zig:30:9: note: consider using 'const'
src/zwmcmd.zig:28:9: error: local variable is never mutated
    var display: *c.Display = c.XOpenDisplay(null) orelse return; // TODO Error
        ^~~~~~~
src/zwmcmd.zig:28:9: note: consider using 'const'
make: *** [makefile:4: zwmcmd] Error 1
```

### PR DESCRIPTION
**Pull request by COD3HUNT3R**
I don't know zig at all. So don't know if anything is wrong with this.

Fixes #5

### CODE REVIEW

**Comment by Eloitor** [comment]
I will review it soon! Thank you :)

File: src/zwm.zig [hunk 1]
```diff
@@ -305,18 +307,18 @@ fn manageWindow(window: c.Window, window_attrs: c.XWindowAttributes, display: *c
...
         if (c.XGetTextProperty(display, window, &tp, AtomNetWMName) == 0) {
             print("Title of client could not be read from EWMH\n", .{});
-            var XA_WM_NAME: c.Atom = 39;
+            const XA_WM_NAME: c.Atom = 39;
             if (c.XGetTextProperty(display, window, &tp, XA_WM_NAME) != 0)
                 print("Title of client  could not be read from ICCCM\n", .{});
         }
         if (tp.nitems == 0)
-            std.mem.copy(u8, cl.name[0..25], "NAME UNKNOWN");
+            std.mem.copyForwards(u8, cl.name[0..25], "NAME UNKNOWN");
```
Comment (Eloitor) [inline src/zwm.zig:318]: I think we should use `@memcpy` instead. 
https://www.openmymind.net/Zigs-memcpy-copyForwards-and-copyBackwards/

File: src/zwm.zig [hunk 2]
```diff
@@ -305,18 +307,18 @@ fn manageWindow(window: c.Window, window_attrs: c.XWindowAttributes, display: *c
...
         const XA_STRING: c.Atom = 31;
         if (tp.encoding == XA_STRING) {
-            std.mem.copy(u8, cl.name[0..25], tp.value[0..25]);
+            std.mem.copyForwards(u8, cl.name[0..25], tp.value[0..25]);
```
Comment (Eloitor) [inline src/zwm.zig:321]: I think we should use `@memcpy` instead.
https://www.openmymind.net/Zigs-memcpy-copyForwards-and-copyBackwards/
