### ISSUE TITLE
Can't build with zig 15.1

### ISSUE THREAD

**Issue by COD3HUNT3R** [Eloitor/MyWindowManager#5]
```
zig build-exe src/zwmcmd.zig -lc -lX11 -lXft -I/usr/include/freetype2
src/zwmcmd.zig:11:9: error: local variable is never mutated
    var arg_one = args.next() orelse return usage();
        ^~~~~~~
src/zwmcmd.zig:11:9: note: consider using 'const'
src/zwmcmd.zig:30:9: error: local variable is never mutated
    var root = c.XDefaultRootWindow(display);
        ^~~~
src/zwmcmd.zig:30:9: note: consider using 'const'
src/zwmcmd.zig:28:9: error: local variable is never mutated
    var display: *c.Display = c.XOpenDisplay(null) orelse return; // TODO Error
        ^~~~~~~
src/zwmcmd.zig:28:9: note: consider using 'const'
make: *** [makefile:4: zwmcmd] Error 1
```

**Comment by Eloitor** [comment]
Wow! thanks for trying it :)

I don't have time right now, but I'll take a look at it later.
If you want to change `var` to `const` and test if it works, you could create a PR :)
